### PR TITLE
Changed A3C networks to Nature paper version

### PR DESCRIPTION
**Pull request by sahiliitm**
Hi. The original A3C paper used Nature version of DQN and not the NIPS version as in this repo. I've changed the network to reflect that. Feel free to accept the PR.

### CODE REVIEW

**Comment by joabim** [comment]
@sahiliitm Are you sure? According to the Experimental Setup section, they refer to the article Playing atari with deep reinforcement learning by Volodymyr et al. from 2013, i.e. the NIPS version. However, they use the preprocessing from the Nature article

**Comment by miyosuda** [comment]
As far as I see the original paper (version 2) page 12, it seems that they are using NIPS setting as @joabim says.

> The agents used the network architecture from (Mnih et al., 2013). 
> The network used a convolutional layer with 16 filters of size 8 × 8 with stride 4, 
> followed by a convolutional layer with with 32 filters of size 4 × 4 with stride 2, 
> followed by a fully connected layer with 256 hidden units.

I'm following this setting.
However, I'm curious about how performance changes with Nature setting.

**Comment by aravindsrinivas** [comment]
https://arxiv.org/pdf/1602.01783.pdf says they use Mnih et al 2015 (which is Nature). In fact, the A3C LSTM uses an additional hidden layer of 256 dimensions after the 512 units over which the LSTM dependency is learnt.

**Comment by miyosuda** [comment]
@aravindsrinivas 
Ah, I see, it is also written in page 5 (section 5.1) as,

> We trained both a feedforward agent with the same architecture as 
> (Mnih et al., 2015; Nair et al., 2015; Van Hasselt et al., 2015) as well as a recurrent agent
> with an additional 256 LSTM cells after the final hidden layer. 

The explanation in section 8 (Experimental Setup) doesn't match this note, but Nature setting is worth trying.
I'll test Nature setting. Thanks.

**Comment by miyosuda** [comment]
I tried Nature setting, but I couldn't get better result than NIPS setting. (I just tried once, so I can't tell that NIPS is always better, but I'll leave current setting as it is for now.)

**Pull request closed without merging**
